# Generated by Django 2.2.6 on 2021-02-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210209_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='auhtor',
        ),
    ]
