# Generated by Django 2.2.6 on 2021-02-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210209_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auhtor',
            new_name='author',
        ),
    ]
