# Generated by Django 2.2.6 on 2021-02-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20210225_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_rate',
        ),
        migrations.AddField(
            model_name='post',
            name='post_rate_avg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postrate',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
